version: "3"
tasks:
  build:
    desc: "Build the project"
    cmds:
      - echo "Building the project..."
      - go build -o bin/blockchain.exe cmd/main.go
  
  runbin:
    desc: "Build and run the binary"
    cmds:
      - ./bin/blockchain.exe --config config/local.yaml

  run:
    desc: "Run the project"
    cmds:
      - echo "Running the project..."
      - go run cmd/main.go --config config/local.yaml
  test:
    desc: "Run tests"
    cmds:
      - echo "Running tests..."
      - go test ./...

  clean:
    desc: "Clean up build artifacts"
    cmds:
      - echo "Cleaning up..."
      - rm -f .\bin\blockchain.exe

  all:
    desc: "Run all tasks"
    deps: [build, test, clean]
